bspranger/Xiaomi

devicetypes/a4refillpad/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
devicetypes/a4refillpad/xiaomi-door-window-sensor.src/xiaomi-door-window-sensor.groovy

- Changed battery percentage for Aqara
- Added date-attribute support for Webcore (Xiaomi and Aqara sensor)
- Changed icon (Xiaomi and Aqara sensor)

Changed battery percentage for Aqara

---

devicetypes/a4refillpad/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
devicetypes/a4refillpad/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy
devicetypes/a4refillpad/xiaomi-door-window-sensor.src/xiaomi-door-window-sensor.groovy
devicetypes/a4refillpad/xiaomi-zigbee-button.src/xiaomi-zigbee-button.groovy

Added the endpointid fingerprint. It seems to make it so that Smartthings will detect and present the Xiaomi device as a valid thing. There's a delay between when the device pairs and when the app shows it as a thing.
Changed the battery calculation to use the average of min and max of the battery value. I was noticing the battery percent ping-ponging between two values, so this will smooth out the reading.

Battery min/max state tracked

---

devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy

Summary Aqara sensors:
- Fixed mixture spaces and tabs. New default is 4 spaces.
- Fixed 'prssure' typo.
- New Tiles layout.
- Code & comments clean-up.

Code clean-up & New Tiles layout

---

devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy

Hi,
I've figured out the necessary groovy code to add to your DH that allows for immediate parsing of the Aqara door/window sensor's battery voltage when the reset / pairing button is pressed.
After the device is properly paired with SmartThings, a short press of the reset / pairing button results in the sensor sending a non-standard announcement hexadecimal message string which among other things contains the current battery voltage value.
Pressing the button to generate the announcement string does not have any effect on the normal checkin interval and also does not prevent the initial or any subsequent catchall messages that also provide battery voltage data.
Like the open / close and catchall events, the button press announcement event is picked up for parsing via zigbee.getEvent, so …

added battery parse on reset button press

---

devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy
devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-leak-sensor.src/xiaomi-aqara-leak-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy
devicetypes/bspranger/xiaomi-button.src/xiaomi-button.groovy
devicetypes/bspranger/xiaomi-door-window-sensor.src/xiaomi-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-motion-sensor.src/xiaomi-motion-sensor.groovy
devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy
devicetypes/bspranger/xiaomi-zigbee-button.src/xiaomi-zigbee-button.groovy

I have liked the idea since I first found it in the Aeon Multisensor 6 (Advanced) DH, So I like to add it too all my DHs that don't run locally. Only have door contacts and buttons so cant test the other DH's

I have added last changed battery date

---

devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy

1. User Schlbuditz on the SmartThings Community forums reported Open/Close Override does not work with this DH (https://community.smartthings.com/t/original-aqara-xiaomi-zigbee-sensors-contact-temp-motion-button-outlet-leak-etc/113253/124?u=veeceeoh). I fixed this by adding the commands to the metadata section which are linked to the override tiles. Also, I noticed that the open override command doesn't update the date/time stamp, so I added that code to the resetOpen() function.
2. As explained in my comment on the current Xiaomi button DH, the configure() and refresh() function code was reading and configuring reporting on the standard battery cluster / attribute (0x0001 / 0x0020) which is not used by Xiaomi devices. So I have changed it here in this DH to configure reporting on the …

Open/close override & config/refresh code fixes

---

devicetypes/bspranger/xiaomi-aqara-leak-sensor.src/xiaomi-aqara-leak-sensor.groovy

This code still has references to Open / Closed from the Door / Window sensor code, so the open / close override tiles don't work, and should actually be changed to  wet / dry override. I've added resetDry and reset Wet commands to the metadata section, and then changed all open / close references to dry / wet so that the override tiles work correctly. Also I added date / time stamp code to the wet override to update the lastWet / lastWetDate states.
Also, I removed the "Refresh" command, because it isn't necessary if the second parameter of the refresh tile definition uses the tileAttribute "device.water".

Fixes to wet / dry override code & refresh command

---

devicetypes/bspranger/xiaomi-aqara-leak-sensor.src/xiaomi-aqara-leak-sensor.groovy

- Fixed wet/dry function
- Changed labels open/close to wet/dry
- Small code clean-up, removed tabs
- Tested device handler

Fixed wet/dry override & code clean-up

---

devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy

- Fixed icon temperature tile (missing in things overview screen)
- Removed 'battery' in label. Consistency for all device handlers
- Code clean-up
- Tested device handler

Added icon back & code clean-up

---

devicetypes/bspranger/xiaomi-aqara-leak-sensor.src/xiaomi-aqara-leak-sensor.groovy

I did some research on state colors and want to revert them. These are the default on standard flood/moisture/leak sensors in ST.

Changed state colors

---

devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy
devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-leak-sensor.src/xiaomi-aqara-leak-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy

Changed layout, fixed location.timeZone & format

---

devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy
devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-leak-sensor.src/xiaomi-aqara-leak-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy
devicetypes/bspranger/xiaomi-button.src/xiaomi-button.groovy
devicetypes/bspranger/xiaomi-door-window-sensor.src/xiaomi-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy

Examples - Hides information they don't need to see

Clean Up App Log (Recently Tab)

---

devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy

Device Handler is broken. This fix removed unwanted ')'.

Broken device handler fix

---

devicetypes/bspranger/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy

For troubleshooting it's great to have this in your 'Recently' log.

Revert my change

---

README.md

• Added "...for SmartThings" to the heading
• Added some periods
• Changed to left justification for images - they looked strange not being under the names of each device.
(I am going to re-crop some of the device images to get them to fill the space better.

Minor edits to Read Me

---

README.md

layout update

---

devicetypes/bspranger/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy

Tested al Aqara Device Handlers, but we forgot to add the dateformat in this one.

Fix: Added dateformat in preferences

---

devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy
devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy

Adding humidity offset for temp/humidity sensors.
Please review before i merge because i am traveling and working on a tablet.

Humidity offset

---

devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy
devicetypes/bspranger/xiaomi-button.src/xiaomi-button.groovy

Fixed virtual button date = now
Made the layouts the same
Made the battery colours the same

Button inconsistencies

---

devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy
devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-button.src/xiaomi-button.groovy
devicetypes/bspranger/xiaomi-door-window-sensor.src/xiaomi-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy

Battery colours all the same on all DH's
opened date added to resetopen function for both contact dh's
improved layout and made layouts the same for both contact dh's

Improvements

---

devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy
devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy

No display of the information yet
untested
#40

Added Min & Max Temp

---

devicetypes/bspranger/xiaomi-mijia-honeywell-fire-detector.src/xiaomi-mijia-honeywell-fire-detector.groovy

fire becomes smoke
smoke becomes detected

address SHM issue maybe

---

devicetypes/bspranger/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy

After discussion in https://github.com/bspranger/Xiaomi/issues/89 - proposing blue scale background colors for lux.

Update xiaomi-aqara-motion-sensor to add background colors for lux/illuminance

---

devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy
devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-leak-sensor.src/xiaomi-aqara-leak-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy
devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy
devicetypes/bspranger/xiaomi-button.src/xiaomi-button.groovy
devicetypes/bspranger/xiaomi-door-window-sensor.src/xiaomi-door-window-sensor.groovy
devicetypes/bspranger/xiaomi-mijia-honeywell-fire-detector.src/xiaomi-mijia-honeywell-fire-detector.groovy
devicetypes/bspranger/xiaomi-motion-sensor.src/xiaomi-motion-sensor.groovy
devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy

This is discussed in 
https://github.com/bspranger/Xiaomi/issues/104
Basically want to change text from 
descriptionText : "${device.displayName} is at ${roundedPct}% (${rawVolts} Volts)"
to
descriptionText : "${device.displayName} Battery at ${roundedPct}% (${rawVolts} Volts)"
so that the word "Battery" shows in the update.   See images and explanation on the issue. 
Figured I'd try my hand at a multi-file commit/pull. 
Please review.
Thanks!

Slight change to Battery reporting in recently 

---

devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy
devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy

Change temp colors to the same standard as Smartthings use for their devices. Works with both C and F

Change temp colors to standard

---

README.md

Readme images now link to their respective folder when clicked. Is a small quality of life update since I kept clicking the large images.

update readme to link images

---

devicetypes/bspranger/xiaomi-zigbee-outlet.src/xiaomi-zigbee-outlet.groovy

Added current electricity load to Xiaomi Zigbee power outlet. The packet appears to only be sent when there is a significant change in load, so not sure exactly how accurate the readings are however.

Add power metering to power outlet
